package miumiu_app;

import data.Acceso;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.Locale;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import static miumiu_app.Menu.clip1;
import static miumiu_app.Menu.clip2;
import static miumiu_app.Menu.pixelMplus;
import org.netbeans.validation.api.builtin.stringvalidation.NombreValidator;
import org.netbeans.validation.api.builtin.stringvalidation.NumeroValidator;
import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.ui.ValidationGroup;
import org.openide.util.Exceptions;

/**
 * Ventana del formulario para comenzar una nueva partida
 * @author Lourdes Navarro Tocón
 */
public class Datos extends javax.swing.JFrame {
    
    File xml; //Imagen del icono de la ventana
    ImageIcon img; //Archivo xml donde se guardan los datos del personaje
    static String MiuMiuName; //String donde se va a guardar el nombre del personaje

    /**
     * Constructor
     * 
     * @throws javax.sound.sampled.UnsupportedAudioFileException UnsupportedAudioFileException
     * @throws java.io.IOException IOException
     * @throws javax.sound.sampled.LineUnavailableException LineUnavailableException
     */
    @SuppressWarnings("unchecked")
    public Datos() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        xml = new File("src/data/save.xml");
        
        img = new ImageIcon("src/resources/icon.png");
        
        initComponents();
        
        float[] gris = new float[3];
        Color.RGBtoHSB(204, 204, 204, gris);
        btnNext.setBackground(Color.getHSBColor(gris[0], gris[1], gris[2]));
        btnNext.setEnabled(false); //Ponemos el botón para continuar deshabilitado por defecto
        
        //Uso de la librería Validation API.
        //Colocamos en la ventana un panel donde se mostrarán los mensajes de error
        //Definimos lo que queremos validar en cada campo del formulario
        //El botón de continuar no se habilitará hasta que sea válido el contenido de los campos a rellenar
        ValidationGroup group = validationPanel.getValidationGroup();
        group.add(fieldName, StringValidators.REQUIRE_NON_EMPTY_STRING, new NombreValidator());
        group.add(fieldAge, StringValidators.REQUIRE_NON_EMPTY_STRING, StringValidators.REQUIRE_VALID_INTEGER, StringValidators.REQUIRE_NON_NEGATIVE_NUMBER, new NumeroValidator());
        group.add(fieldMMName, StringValidators.REQUIRE_NON_EMPTY_STRING, new NombreValidator());
    
        validationPanel.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                if(validationPanel.getProblem()==null){
                    btnNext.setBackground(Color.WHITE);
                    btnNext.setEnabled(true);
                } else {
                    float[] gris = new float[3];
                    Color.RGBtoHSB(204, 204, 204, gris);
                    btnNext.setBackground(Color.getHSBColor(gris[0], gris[1], gris[2]));
                    btnNext.setEnabled(false);
                }
            }
        });
        
        //Abrimos el archivo xml para obtener los datos y manejarlos 
        Acceso.abrirXML(xml);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIS = new javax.swing.JPanel();
        lbLogIn = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        validationPanel = new org.netbeans.validation.api.ui.swing.ValidationPanel();
        lbAge = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lbLogIn1 = new javax.swing.JLabel();
        fieldMMName = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiuMiu");
        setIconImage(img.getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));

        panelIS.setBackground(new java.awt.Color(254, 236, 214));

        lbLogIn.setFont(pixelMplus);
        lbLogIn.setForeground(new java.awt.Color(118, 156, 196));
        lbLogIn.setText("¡Tu MiuMiu está a punto de nacer!");

        lbName.setFont(pixelMplus);
        lbName.setForeground(new java.awt.Color(105, 171, 99));
        lbName.setText("Tu nombre:");

        fieldName.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fieldName.setForeground(new java.awt.Color(153, 153, 153));
        fieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldNameKeyPressed(evt);
            }
        });

        validationPanel.setBackground(new java.awt.Color(254, 236, 214));

        lbAge.setFont(pixelMplus);
        lbAge.setForeground(new java.awt.Color(163, 159, 225));
        lbAge.setText("Tu edad:");

        fieldAge.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fieldAge.setForeground(new java.awt.Color(153, 153, 153));
        fieldAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldAgeKeyPressed(evt);
            }
        });

        lbLogIn1.setFont(pixelMplus);
        lbLogIn1.setForeground(new java.awt.Color(255, 102, 153));
        lbLogIn1.setText("Tu MiuMiu se llamará...");

        fieldMMName.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        fieldMMName.setForeground(new java.awt.Color(153, 153, 153));
        fieldMMName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldMMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldMMNameKeyPressed(evt);
            }
        });

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setForeground(new java.awt.Color(105, 171, 99));
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/check.png"))); // NOI18N
        btnNext.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 171, 99), 1, true));
        btnNext.setContentAreaFilled(false);
        btnNext.setOpaque(true);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        btnBack.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 1, true));
        btnBack.setContentAreaFilled(false);
        btnBack.setOpaque(true);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelISLayout = new javax.swing.GroupLayout(panelIS);
        panelIS.setLayout(panelISLayout);
        panelISLayout.setHorizontalGroup(
            panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelISLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelISLayout.createSequentialGroup()
                        .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelISLayout.createSequentialGroup()
                                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbName)
                                    .addComponent(lbAge))
                                .addGap(52, 52, 52)
                                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(validationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelISLayout.createSequentialGroup()
                        .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLogIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panelISLayout.createSequentialGroup()
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(70, 70, 70)
                                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16))
                                .addComponent(fieldMMName, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(155, 155, 155))))
        );
        panelISLayout.setVerticalGroup(
            panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelISLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(validationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName))
                .addGap(45, 45, 45)
                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAge))
                .addGap(45, 45, 45)
                .addComponent(lbLogIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldMMName, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelISLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para empezar la partida una vez rellenado el formulario al darle al botón de siguiente
     * @param evt 
     */
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        clip2.start(); //Sonido del botón
        clip2.setFramePosition(0);
        MiuMiuName = fieldMMName.getText(); //Almacenamos el nombre del campo del nombre del personaje
        Acceso.guardarDatos(MiuMiuName, 10, 10, 0, 90, 10, 0, 1); //Guardamos el nombre y los stats por defecto
        Acceso.sobreescribir();
        Juego newGame;
        try {
            newGame = new Juego(); //Cerramos el formulario y comienza una nueva partida
            newGame.setVisible(true);
            this.setVisible(false);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * Método para acceder al siguiente campo del formulario al pulsar las teclas de enter y abajo
     * @param evt Key Event
     */
    private void fieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            fieldAge.requestFocus();
        }
    }//GEN-LAST:event_fieldNameKeyPressed

    /**
     * Método para acceder al anterior campo del formulario al pulsar la tecla arriba y al siguiente
     * al pulsar las teclas de enter y abajo
     * @param evt Key Event
     */
    private void fieldAgeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldAgeKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_DOWN){
            fieldMMName.requestFocus();
        } else if(evt.getKeyCode()==KeyEvent.VK_UP){
            fieldName.requestFocus();
        }
    }//GEN-LAST:event_fieldAgeKeyPressed

    /**
     * Método para volver a la ventana del menú al pulsar la tecla de ir atrás
     * @param evt Action Event
     */
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        clip2.start(); //Sonido del botón
        clip2.setFramePosition(0);
        clip1.stop();
        this.dispose(); //Cerramos la ventana del formulario y abrimos una nueva ventana del menú
        Menu m;
        try {
            m = new Menu();
            m.setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * Método para acceder al anterior campo del formulario al pulsar la tecla de arriba
     * @param evt Key Event
     */
    private void fieldMMNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldMMNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP){
            fieldAge.requestFocus();
        }
    }//GEN-LAST:event_fieldMMNameKeyPressed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException IOException
     * @throws javax.sound.sampled.UnsupportedAudioFileException UnsupportedAudioFileException
     * @throws javax.sound.sampled.LineUnavailableException LineUnavailableException
     */
    public static void main(String args[]) throws IOException, UnsupportedAudioFileException, LineUnavailableException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Datos().setVisible(true);
                } catch (IOException | UnsupportedAudioFileException | LineUnavailableException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });
        
        //Establecemos el Locale de la aplicación
        Locale.setDefault(new Locale("es", "ES"));
        try {
            new Datos().setVisible(true);
        } catch (IOException | UnsupportedAudioFileException | LineUnavailableException ex) {
            Exceptions.printStackTrace(ex);
        }
        
        //Definimos la fuente que importamos
        try{
            pixelMplus = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/PixelMplus10-Regular.ttf")).deriveFont(30f);	
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/PixelMplus10-Regular.ttf")));			
	} catch(IOException | FontFormatException e){
            e.printStackTrace();
	}
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldMMName;
    private javax.swing.JTextField fieldName;
    private javax.swing.JLabel lbAge;
    private javax.swing.JLabel lbLogIn;
    private javax.swing.JLabel lbLogIn1;
    private javax.swing.JLabel lbName;
    private javax.swing.JPanel panelIS;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel;
    // End of variables declaration//GEN-END:variables
}
