package miumiu_app;

import data.Acceso;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import org.openide.util.Exceptions;

/**
 * Ventana del menú principal de la aplicación
 * 
 * @author Lourdes Navarro Tocón
 */
public class Menu extends javax.swing.JFrame {
    
    ImageIcon img; //Imagen del icono de la ventana
    File xml; //Archivo xml donde se guardan los datos del personaje
    static Font pixelMplus; //Fuente a incluir
    AudioInputStream audioMenu; //Audio de la música del menú
    static Clip clip1; //Clip de la música del menú
    AudioInputStream audioClick; //Audio del sonido de los botones
    static Clip clip2; //Clip del sonido de los botonoes
    
    /**
     * Constructor
     * @throws javax.sound.sampled.UnsupportedAudioFileException UnsupportedAudioFileException
     * @throws java.io.IOException IOException
     * @throws javax.sound.sampled.LineUnavailableException LineUnavailableException
     */
    public Menu() throws UnsupportedAudioFileException, IOException, LineUnavailableException {
        xml = new File("src/data/save.xml");
        
        img = new ImageIcon("src/resources/icon.png");
        
        clip2 = AudioSystem.getClip();
        audioClick = AudioSystem.getAudioInputStream(new File("src/resources/sounds/click.wav"));
        clip1 = AudioSystem.getClip();
        audioMenu = AudioSystem.getAudioInputStream(new File("src/resources/sounds/menu.wav"));
        initComponents();
        
        clip1.open(audioMenu);
        clip2.open(audioClick);
        //Se reproduce el clip del menú en loop
        clip1.start();
        clip1.loop(-1);
        
        //Abrimos el archivo xml para obtener los datos y manejarlos
        Acceso.abrirXML(xml);
        String[] datos = Acceso.obtenerDatos();
        //Si los datos del xml son los predeterminados significa que no hay ninguna partida guardada, por lo que no se puede continuar
        if(datos[1].equals("0.0") && datos[1].equals("0.0") && datos[2].equals("0.0") && datos[3].equals("0.0") && datos[4].equals("0.0") && datos[5].equals("0.0") && datos[6].equals("0.0")){
            float[] gris = new float[3];
            Color.RGBtoHSB(204, 204, 204, gris);
            btnCont.setBackground(Color.getHSBColor(gris[0], gris[1], gris[2]));
            btnCont.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPpal = new javax.swing.JPanel();
        iconPpal = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnCont = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiuMiu");
        setIconImage(img.getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(700, 600));

        panelPpal.setBackground(new java.awt.Color(254, 236, 214));
        panelPpal.setPreferredSize(new java.awt.Dimension(600, 800));

        iconPpal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ppal.gif"))); // NOI18N

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/title.png"))); // NOI18N

        btnNew.setBackground(new java.awt.Color(255, 255, 255));
        btnNew.setFont(pixelMplus);
        btnNew.setForeground(new java.awt.Color(105, 171, 99));
        btnNew.setText("Nuevo");
        btnNew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 171, 99), 1, true));
        btnNew.setContentAreaFilled(false);
        btnNew.setOpaque(true);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnCont.setBackground(new java.awt.Color(255, 255, 255));
        btnCont.setFont(pixelMplus);
        btnCont.setForeground(new java.awt.Color(155, 184, 237));
        btnCont.setText("Continuar");
        btnCont.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(155, 184, 237), 1, true));
        btnCont.setContentAreaFilled(false);
        btnCont.setOpaque(true);
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPpalLayout = new javax.swing.GroupLayout(panelPpal);
        panelPpal.setLayout(panelPpalLayout);
        panelPpalLayout.setHorizontalGroup(
            panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPpalLayout.createSequentialGroup()
                .addGroup(panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPpalLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addGroup(panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCont, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelPpalLayout.createSequentialGroup()
                            .addGap(219, 219, 219)
                            .addComponent(iconPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        panelPpalLayout.setVerticalGroup(
            panelPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPpalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(iconPpal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCont, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método para iniciar una nueva partida cuando pulsamos el botón de "Nuevo"
     * @param evt Action Event
     */
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clip2.start(); //Sonido del botón
        clip2.setFramePosition(0);
        this.setVisible(false);
        Datos init;
        try {
            init = new Datos(); //Al pulsar "Nuevo" nos llevará a la ventana del formulario
            init.setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * Método para continuar la partida anteriormente guardada al pulsar el botón de "Continuar"
     * @param evt Action Event
     */
    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        // TODO add your handling code here:
        clip2.start(); //Sonido del botón
        clip2.setFramePosition(0);
        this.setVisible(false); //Cierra la ventana del menú y abre la de la partida
        Juego game;
        try {
            game = new Juego(); 
            game.setVisible(true);
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_btnContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (IOException | UnsupportedAudioFileException | LineUnavailableException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });
        
        //Definimos la fuente que importamos
        try{
            pixelMplus = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/PixelMplus10-Regular.ttf")).deriveFont(30f);	
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/PixelMplus10-Regular.ttf")));			
	} catch(IOException | FontFormatException e){
            e.printStackTrace();
	}
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel iconPpal;
    private javax.swing.JPanel panelPpal;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
